/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import dao.FornecedorDAO;
import entidades.Fornecedor;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class IfrFornecedor extends javax.swing.JInternalFrame {
    int idFornecedor = 0;
    /**
     * Creates new form IfrFornecedor
     */
    public IfrFornecedor() {
        initComponents();
        carregarDados();
    }
    
    private void carregarDados() {
        new FornecedorDAO().popularTabela(tabelaFornecedor, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        fieldSearchFornecedor = new javax.swing.JTextField();
        buttonPesquisarFornecedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdNomeFornecedor = new javax.swing.JTextField();
        tfdEmailFornecedor = new javax.swing.JTextField();
        tfdCnpjFornecedor = new javax.swing.JTextField();
        tfdTelefoneFornecedor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setTitle("Cadastro de Fornecedores");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaFornecedor);

        jLabel5.setText("Filtrar:");

        buttonPesquisarFornecedor.setText("Pesquisar");
        buttonPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSearchFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPesquisarFornecedor)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldSearchFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPesquisarFornecedor))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar fornecedores", jPanel1);

        jLabel1.setText("Nome:");

        jLabel2.setText("Email:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("CNPJ:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(tfdEmailFornecedor)
                            .addComponent(tfdCnpjFornecedor)
                            .addComponent(tfdTelefoneFornecedor)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfdCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar fornecedor", jPanel2);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valueNome = tfdNomeFornecedor.getText();
        String valueEmail = tfdEmailFornecedor.getText();
        String valueCnpj = tfdCnpjFornecedor.getText();
        String valueTelefone = tfdTelefoneFornecedor.getText();
        
        if(valueNome.isBlank()) {
            JOptionPane.showMessageDialog(this, "O nome não pode ser vazio");
            tfdNomeFornecedor.requestFocus();
            return;
        }
        
        if(valueEmail.isBlank()) {
            JOptionPane.showMessageDialog(this, "A descrição do endereço de email não pode ser vazia");
            tfdEmailFornecedor.requestFocus();
            return;
        }
        
        if(valueCnpj.isBlank()) {
            JOptionPane.showMessageDialog(this, "O CNPJ não pode ser vazio");
            tfdCnpjFornecedor.requestFocus();
            return;
        }
        
        if(valueTelefone.isBlank()) {
            JOptionPane.showMessageDialog(this, "O telefone não pode ser vazio");
            tfdTelefoneFornecedor.requestFocus();
            return;
        }
        
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setId(idFornecedor);
        fornecedor.setNome(valueNome);
        fornecedor.setEmail(valueEmail);
        fornecedor.setCnpj(valueCnpj);
        fornecedor.setTelefone(valueTelefone);
        
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        
        if(idFornecedor == 0) {
            if(fornecedorDAO.salvar(fornecedor) == null) {
                tfdNomeFornecedor.setText("");
                tfdEmailFornecedor.setText("");
                tfdCnpjFornecedor.setText("");
                tfdTelefoneFornecedor.setText("");

                JOptionPane.showMessageDialog(this, "Fornecedor adicionado com sucesso");

                carregarDados();
                tfdNomeFornecedor.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do Fornecedor");
            }
        } else {
            if(fornecedorDAO.atualizar(fornecedor) == null) {
                tfdNomeFornecedor.setText("");
                tfdEmailFornecedor.setText("");
                tfdCnpjFornecedor.setText("");
                tfdTelefoneFornecedor.setText("");

                JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso");

                carregarDados();
                tfdNomeFornecedor.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizado dados do Fornecedor");
            }
        }
        idFornecedor = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisarFornecedorActionPerformed
        new FornecedorDAO().popularTabela(tabelaFornecedor, fieldSearchFornecedor.getText());
    }//GEN-LAST:event_buttonPesquisarFornecedorActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        String idTabela = String.valueOf(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 0));
        
        idFornecedor = Integer.parseInt(idTabela);
        Fornecedor fornecedor = new FornecedorDAO().consultarId(idFornecedor);
        
        if(fornecedor != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            tfdNomeFornecedor.setText(fornecedor.getNome());
            tfdEmailFornecedor.setText(fornecedor.getEmail());
            tfdCnpjFornecedor.setText(fornecedor.getCnpj());
            tfdTelefoneFornecedor.setText(fornecedor.getTelefone());
            
            tfdNomeFornecedor.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do fornecedor não encontrado");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String idTabela = String.valueOf(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 0));
        
        idFornecedor = Integer.parseInt(idTabela);
        String fornecedor = new FornecedorDAO().excluir(idFornecedor);
        if(fornecedor == null) {
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso");
            
            carregarDados();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir o registro");
        }
        
        idFornecedor = 0;
    }//GEN-LAST:event_buttonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JButton buttonPesquisarFornecedor;
    private javax.swing.JTextField fieldSearchFornecedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaFornecedor;
    private javax.swing.JTextField tfdCnpjFornecedor;
    private javax.swing.JTextField tfdEmailFornecedor;
    private javax.swing.JTextField tfdNomeFornecedor;
    private javax.swing.JTextField tfdTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
