/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.IItemPesquisa;
import apoio.Validacao;
import dao.ItemPedidoDAO;
import dao.PedidoDAO;
import entidades.ItemPedido;
import entidades.Pedido;
import java.awt.Color;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elias
 */
public class IfrPedido extends javax.swing.JInternalFrame implements IItemPesquisa {
    int idPedido = 0;
    private DefaultTableModel model;
    private List<ItemPedido> itensPedido = new ArrayList<>();
    
    /**
     * Creates new form IfrPessoa
     */
    public IfrPedido() {
        initComponents();
        
        Formatacao.formatarData(formattedDataInput);
        tfdIdProduto.setEditable(false);
        tfdDescricaoProduto.setEditable(false);
        tfdValorProduto.setEditable(false);
        tfdTotal.setEditable(false);
        
        new CombosDAO().popularCombo("cliente", comboBoxClientes);
        carregarDados();
        
        inicializarTabela();
    }
    
    private void carregarDados() {
        new PedidoDAO().popularTabela(tblPedido, "");
    }
    
    private void inicializarTabela() {
        model = new DefaultTableModel(new Object[]{"Id", "Produto", "Quantidade", "Preço"}, 0);
        tabelaProdutos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdObsevacaoPedido = new javax.swing.JTextField();
        tfdEnderecoPedido = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        formattedDataInput = new javax.swing.JFormattedTextField();
        comboBoxClientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfdQuantidade = new javax.swing.JTextField();
        tfdIdProduto = new javax.swing.JTextField();
        tfdDescricaoProduto = new javax.swing.JTextField();
        tfdValorProduto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfdTotal = new javax.swing.JTextField();
        buttonExcluir = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        setTitle("Cadastro de Pedidos");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPedido);

        jLabel5.setText("Filtrar:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton4.setText("Exibir detalhes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar Pedidos", jPanel1);

        jLabel1.setText("Observação:");

        jLabel2.setText("Endereço:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Data:");

        formattedDataInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedDataInputFocusLost(evt);
            }
        });

        comboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cliente ID:");

        jButton3.setText("Buscar produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Produto", "Quantidade", "Preço"
            }
        ));
        jScrollPane4.setViewportView(tabelaProdutos);

        jLabel8.setText("Produto:");

        jLabel9.setText("Quantidade:");

        tfdIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdIdProdutoActionPerformed(evt);
            }
        });

        jButton6.setText("Adicionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Remover");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdEnderecoPedido)
                            .addComponent(formattedDataInput)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfdObsevacaoPedido)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(tfdQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addComponent(tfdDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfdValorProduto)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(formattedDataInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfdEnderecoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdObsevacaoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfdQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Adicionar Pedido", jPanel2);

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valueObservacao  = tfdObsevacaoPedido.getText();
        String valueEnderecoEntrega  = tfdEnderecoPedido.getText();
        String valueData = formattedDataInput.getText();
        
        if(valueData.isBlank()) {
            JOptionPane.showMessageDialog(this, "A data não pode ser vazia");
            formattedDataInput.requestFocus();
            return;
        }
        
        if(valueEnderecoEntrega.isBlank()) {
            JOptionPane.showMessageDialog(this, "O endereço de entrega não pode ser vazio");
            tfdEnderecoPedido.requestFocus();
            return;
        }
        
        if(valueObservacao.isBlank()) {
            JOptionPane.showMessageDialog(this, "A observação não pode ser vazia");
            tfdObsevacaoPedido.requestFocus();
            return;
        }
        
         // Convert the date to the correct format
        SimpleDateFormat inputFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDate;
        try {
            java.util.Date date = inputFormat.parse(valueData);
            formattedDate = outputFormat.format(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.");
            formattedDataInput.requestFocus();
            return;
        }
        
        Pedido pedido = new Pedido();
        pedido.setId(idPedido);
        pedido.setData(formattedDate);
        pedido.setEndereco_entrega(valueEnderecoEntrega);
        pedido.setObservacao(valueObservacao);
        ComboItem ci = (ComboItem) comboBoxClientes.getSelectedItem();
        pedido.setClient_id(ci.getCodigo());
        
        PedidoDAO pedidoDAO = new PedidoDAO();
        
        if (idPedido == 0) {
            String result = pedidoDAO.salvar(pedido);
            try {
                int idPedidoGerado = Integer.parseInt(result);
                pedido.setId(idPedidoGerado);
                formattedDataInput.setText("");
                tfdEnderecoPedido.setText("");
                tfdObsevacaoPedido.setText("");
                comboBoxClientes.setSelectedIndex(0);

                // Salvando os itens do pedido
                ItemPedidoDAO itemPedidoDAO = new ItemPedidoDAO();
                for (ItemPedido item : itensPedido) {
                    item.setPedido_id(pedido.getId());
                    itemPedidoDAO.salvar(item);
                }

                JOptionPane.showMessageDialog(this, "Pedido adicionado com sucesso");

                carregarDados();
                formattedDataInput.requestFocus();
                atualizarTotal();
                
                model.setRowCount(0);
                itensPedido.clear();
                tfdTotal.setText("");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do pedido: " + result);
            }
        } else {
            if(pedidoDAO.atualizar(pedido) == null) {
                formattedDataInput.setText("");
                tfdObsevacaoPedido.setText("");
                tfdEnderecoPedido.setText("");
                comboBoxClientes.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Pedido atualizado com sucesso");

                carregarDados();
                formattedDataInput.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do pedido");
            }
        }
        
        idPedido = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new PedidoDAO().popularTabela(tblPedido, tfdSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));
        
        idPedido = Integer.parseInt(idTabela);
        Pedido pedido = new PedidoDAO().consultarId(idPedido);
        
        if(pedido != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            String dataBancoDeDadosFormated = Formatacao.formatarData(pedido.getData());
            
            formattedDataInput.setText(dataBancoDeDadosFormated);
            tfdEnderecoPedido.setText(pedido.getEndereco_entrega());
            tfdObsevacaoPedido.setText(pedido.getObservacao());
            ComboItem item = new ComboItem();
            item.setCodigo(pedido.getClient_id());
            new CombosDAO().definirItemCombo(comboBoxClientes, item);
            
            
            formattedDataInput.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do pedido não encontrado");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    
    
    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));
        
        idPedido = Integer.parseInt(idTabela);
        String pedido = new PedidoDAO().excluir(idPedido);
        
        if(pedido == null) {
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso");
            
            carregarDados();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir o registro");
        }
        
        idPedido = 0;
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void formattedDataInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedDataInputFocusLost
        if(!Validacao.validarDataFormatada(formattedDataInput.getText())) {
            formattedDataInput.setBackground(Color.red);
        } else {
            formattedDataInput.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_formattedDataInputFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new DlgLocalizar(null, true, this, "produto").setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfdIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdIdProdutoActionPerformed

    private void atualizarTotal() {
        double total = 0;
        for (ItemPedido item : itensPedido) {
            total += Double.parseDouble(item.getValor_item());
        }
        tfdTotal.setText(String.valueOf(total));
        tfdIdProduto.setText("");
        tfdQuantidade.setText("");
        tfdDescricaoProduto.setText("");
        tfdValorProduto.setText("");
    }
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(tfdIdProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Escolha algum produto.");
            return;
        }
        
        if(tfdQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Adicione uma quantidade ao produto.");
            return;
        }
        
        int idProduto = Integer.parseInt(tfdIdProduto.getText());
        String descricaoProduto = tfdDescricaoProduto.getText();
        double valorUnitario = Double.parseDouble(tfdValorProduto.getText());
        double quantidade = Double.parseDouble(tfdQuantidade.getText());
        double precoTotal = valorUnitario * quantidade;

        ItemPedido item = new ItemPedido();
        item.setProduto_id(idProduto);
        item.setQtde(quantidade);
        item.setValor_item(String.valueOf(precoTotal));

        itensPedido.add(item);

        model.addRow(new Object[]{idProduto, descricaoProduto, quantidade, precoTotal});
        
        atualizarTotal();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int selectedRow = tabelaProdutos.getSelectedRow();
        if (selectedRow >= 0) {
            itensPedido.remove(selectedRow);
            model.removeRow(selectedRow);
            atualizarTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto para remover.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));
            int idVenda =  Integer.parseInt(idTabela);

            Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(tblPedido);
            ModalDetalhesPedidos modal = new ModalDetalhesPedidos(parentFrame, true, idVenda);
            modal.setVisible(true);
        } catch(Exception e) {
         JOptionPane.showMessageDialog(this, "Selecione alguma linha na tabela para ver seus detalhes!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    @Override
    public void definirValor(String[] valores, String itemPesquisa) {
        if (itemPesquisa.equalsIgnoreCase("produto")) {
            tfdIdProduto.setText(valores[0]);
            tfdDescricaoProduto.setText(valores[1]);
            tfdValorProduto.setText(valores[2]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JComboBox<String> comboBoxClientes;
    private javax.swing.JFormattedTextField formattedDataInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField tfdDescricaoProduto;
    private javax.swing.JTextField tfdEnderecoPedido;
    private javax.swing.JTextField tfdIdProduto;
    private javax.swing.JTextField tfdObsevacaoPedido;
    private javax.swing.JTextField tfdQuantidade;
    private javax.swing.JTextField tfdSearch;
    private javax.swing.JTextField tfdTotal;
    private javax.swing.JTextField tfdValorProduto;
    // End of variables declaration//GEN-END:variables
}
