/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import apoio.Validacao;
import dao.PedidoDAO;
import entidades.Pedido;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Elias
 */
public class IfrPedido extends javax.swing.JInternalFrame {
    int idPedido = 0;
    /**
     * Creates new form IfrPessoa
     */
    public IfrPedido() {
        initComponents();
        
        Formatacao.formatarData(formattedDataInput);
        
        new CombosDAO().popularCombo("cliente", comboBoxClientes);
        carregarDados();
    }
    
    private void carregarDados() {
        new PedidoDAO().popularTabela(tblPedido, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdObsevacaoPedido = new javax.swing.JTextField();
        tfdEnderecoPedido = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        formattedDataInput = new javax.swing.JFormattedTextField();
        comboBoxClientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buttonEditar = new javax.swing.JButton();
        buttonExcluir = new javax.swing.JButton();

        setTitle("Cadastro de Pedidos");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPedido);

        jLabel5.setText("Filtrar:");

        btnSearch.setText("Pesquisar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar Pedidos", jPanel1);

        jLabel1.setText("Observação:");

        jLabel2.setText("Endereço:");

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Data:");

        formattedDataInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedDataInputFocusLost(evt);
            }
        });

        comboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Cliente ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdEnderecoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(formattedDataInput)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfdObsevacaoPedido))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(formattedDataInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfdEnderecoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdObsevacaoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Adicionar Pedido", jPanel2);

        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        buttonExcluir.setText("Excluir");
        buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(buttonEditar)
                    .addComponent(buttonExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String valueObservacao  = tfdObsevacaoPedido.getText();
        String valueEnderecoEntrega  = tfdEnderecoPedido.getText();
        String valueData = formattedDataInput.getText();
        
        if(valueData.isBlank()) {
            JOptionPane.showMessageDialog(this, "A data não pode ser vazia");
            formattedDataInput.requestFocus();
            return;
        }
        
        if(valueEnderecoEntrega.isBlank()) {
            JOptionPane.showMessageDialog(this, "O endereço de entrega não pode ser vazio");
            tfdEnderecoPedido.requestFocus();
            return;
        }
        
        if(valueObservacao.isBlank()) {
            JOptionPane.showMessageDialog(this, "A observação não pode ser vazia");
            tfdObsevacaoPedido.requestFocus();
            return;
        }
        
        Pedido pedido = new Pedido();
        pedido.setId(idPedido);
        pedido.setData(valueData);
        pedido.setEndereco_entrega(valueEnderecoEntrega);
        pedido.setObservacao(valueObservacao);
        ComboItem ci = (ComboItem) comboBoxClientes.getSelectedItem();
        pedido.setClient_id(ci.getCodigo());
        
        PedidoDAO pedidoDAO = new PedidoDAO();
        
        if(idPedido == 0) {
            if(pedidoDAO.salvar(pedido) == null) {
                formattedDataInput.setText("");
                tfdEnderecoPedido.setText("");
                tfdObsevacaoPedido.setText("");
                comboBoxClientes.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Pedido adicionado com sucesso");

                carregarDados();
                formattedDataInput.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do pedido");
            }
        } else {
            if(pedidoDAO.atualizar(pedido) == null) {
                formattedDataInput.setText("");
                tfdObsevacaoPedido.setText("");
                tfdEnderecoPedido.setText("");
                comboBoxClientes.setSelectedIndex(0);

                JOptionPane.showMessageDialog(this, "Pedido atualizado com sucesso");

                carregarDados();
                formattedDataInput.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar dados do pedido");
            }
        }
        
        idPedido = 0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        new PedidoDAO().popularTabela(tblPedido, tfdSearch.getText());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));
        
        idPedido = Integer.parseInt(idTabela);
        Pedido pedido = new PedidoDAO().consultarId(idPedido);
        
        if(pedido != null) {
            jTabbedPane1.setSelectedIndex(1);
            
            String dataBancoDeDadosFormated = Formatacao.formatarData(pedido.getData());
            
            formattedDataInput.setText(dataBancoDeDadosFormated);
            tfdObsevacaoPedido.setText(pedido.getEndereco_entrega());
            tfdEnderecoPedido.setText(pedido.getObservacao());
            ComboItem item = new ComboItem();
            item.setCodigo(pedido.getClient_id());
            new CombosDAO().definirItemCombo(comboBoxClientes, item);
            
            
            formattedDataInput.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do pedido não encontrado");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed

    
    
    private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirActionPerformed
        String idTabela = String.valueOf(tblPedido.getValueAt(tblPedido.getSelectedRow(), 0));
        
        idPedido = Integer.parseInt(idTabela);
        String pedido = new PedidoDAO().excluir(idPedido);
        
        if(pedido == null) {
            JOptionPane.showMessageDialog(this, "Registro excluido com sucesso");
            
            carregarDados();
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir o registro");
        }
        
        idPedido = 0;
    }//GEN-LAST:event_buttonExcluirActionPerformed

    private void formattedDataInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedDataInputFocusLost
        if(!Validacao.validarDataFormatada(formattedDataInput.getText())) {
            formattedDataInput.setBackground(Color.red);
        } else {
            formattedDataInput.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_formattedDataInputFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JComboBox<String> comboBoxClientes;
    private javax.swing.JFormattedTextField formattedDataInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField tfdEnderecoPedido;
    private javax.swing.JTextField tfdObsevacaoPedido;
    private javax.swing.JTextField tfdSearch;
    // End of variables declaration//GEN-END:variables
}
